In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Vectorized version: " + str(1000 * (toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(len(a)):
    c += a[i] * b[i]
toc = time.time()
print(c)
print("No vectorized version: " + str(1000 * (toc - tic)) + "ms")

250044.066226
Vectorized version: 1.4922618865966797ms
250044.066226
No vectorized version: 586.505651473999ms


In [15]:
A = np.array([[56, 0, 4.4, 68],
             [1.2, 104, 52, 8],
             [1.8, 135, 99, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [17]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [23]:
percentage = 100 * (A / cal.reshape(1, 4))
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [22]:
cal.reshape(1, 4)

array([[  59. ,  239. ,  155.4,   76.9]])

In [25]:
a = np.random.rand(2, 3)
print(a)

[[ 0.67545951  0.7564475   0.54724354]
 [ 0.82288478  0.35837018  0.36138859]]


In [27]:
b = np.random.randn(2, 1)
print(b)

[[-0.31294942]
 [ 0.55338398]]


In [29]:
c = a + b
print(c)
c.shape

[[ 0.36251008  0.44349808  0.23429412]
 [ 1.37626877  0.91175416  0.91477258]]


(2, 3)

In [31]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288, 45)

In [34]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c.shape

(3, 3)